package top.chao.entity;

import java.util.Date;

public class Evaluate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer use_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date publish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer video_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer like_count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.id
     *
     * @return the value of evaluate.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.id
     *
     * @param id the value for evaluate.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.use_id
     *
     * @return the value of evaluate.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUse_id() {
        return use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.use_id
     *
     * @param use_id the value for evaluate.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUse_id(Integer use_id) {
        this.use_id = use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.context
     *
     * @return the value of evaluate.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.context
     *
     * @param context the value for evaluate.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.publish_time
     *
     * @return the value of evaluate.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getPublish_time() {
        return publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.publish_time
     *
     * @param publish_time the value for evaluate.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPublish_time(Date publish_time) {
        this.publish_time = publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.video_id
     *
     * @return the value of evaluate.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getVideo_id() {
        return video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.video_id
     *
     * @param video_id the value for evaluate.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setVideo_id(Integer video_id) {
        this.video_id = video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.like_count
     *
     * @return the value of evaluate.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getLike_count() {
        return like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.like_count
     *
     * @param like_count the value for evaluate.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLike_count(Integer like_count) {
        this.like_count = like_count;
    }
}