package top.chao.entity;

import java.util.Date;

public class EvaluationLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_like.evaluation_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer evaluation_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date like_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_like.Id
     *
     * @return the value of evaluation_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_like.Id
     *
     * @param id the value for evaluation_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_like.evaluation_id
     *
     * @return the value of evaluation_like.evaluation_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getEvaluation_id() {
        return evaluation_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_like.evaluation_id
     *
     * @param evaluation_id the value for evaluation_like.evaluation_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setEvaluation_id(Integer evaluation_id) {
        this.evaluation_id = evaluation_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_like.user_id
     *
     * @return the value of evaluation_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_like.user_id
     *
     * @param user_id the value for evaluation_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_like.like_time
     *
     * @return the value of evaluation_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getLike_time() {
        return like_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_like.like_time
     *
     * @param like_time the value for evaluation_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLike_time(Date like_time) {
        this.like_time = like_time;
    }
}