package top.chao.entity;

import java.util.Date;

public class CollectNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer note_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date collect_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.id
     *
     * @return the value of collect_note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.id
     *
     * @param id the value for collect_note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.user_id
     *
     * @return the value of collect_note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.user_id
     *
     * @param user_id the value for collect_note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.note_id
     *
     * @return the value of collect_note.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getNote_id() {
        return note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.note_id
     *
     * @param note_id the value for collect_note.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setNote_id(Integer note_id) {
        this.note_id = note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.collect_time
     *
     * @return the value of collect_note.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getCollect_time() {
        return collect_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.collect_time
     *
     * @param collect_time the value for collect_note.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCollect_time(Date collect_time) {
        this.collect_time = collect_time;
    }
}