package top.chao.entity;

import java.util.Date;

public class Note {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date publish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer like_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer video_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.title
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.id
     *
     * @return the value of note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.id
     *
     * @param id the value for note.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.publish_time
     *
     * @return the value of note.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getPublish_time() {
        return publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.publish_time
     *
     * @param publish_time the value for note.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPublish_time(Date publish_time) {
        this.publish_time = publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.like_count
     *
     * @return the value of note.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getLike_count() {
        return like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.like_count
     *
     * @param like_count the value for note.like_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLike_count(Integer like_count) {
        this.like_count = like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.user_id
     *
     * @return the value of note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.user_id
     *
     * @param user_id the value for note.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.video_id
     *
     * @return the value of note.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getVideo_id() {
        return video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.video_id
     *
     * @param video_id the value for note.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setVideo_id(Integer video_id) {
        this.video_id = video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.title
     *
     * @return the value of note.title
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.title
     *
     * @param title the value for note.title
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.context
     *
     * @return the value of note.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.context
     *
     * @param context the value for note.context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}