package top.chao.entity;

import java.util.Date;

public class NoteLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer note_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date like_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.Id
     *
     * @return the value of note_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.Id
     *
     * @param id the value for note_like.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.user_id
     *
     * @return the value of note_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.user_id
     *
     * @param user_id the value for note_like.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.note_id
     *
     * @return the value of note_like.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getNote_id() {
        return note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.note_id
     *
     * @param note_id the value for note_like.note_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setNote_id(Integer note_id) {
        this.note_id = note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.like_time
     *
     * @return the value of note_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getLike_time() {
        return like_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.like_time
     *
     * @param like_time the value for note_like.like_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLike_time(Date like_time) {
        this.like_time = like_time;
    }
}