package top.chao.entity;

import java.util.Date;

public class CollectCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_course.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_course.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_course.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer course_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_course.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date collect_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_course.Id
     *
     * @return the value of collect_course.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_course.Id
     *
     * @param id the value for collect_course.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_course.user_id
     *
     * @return the value of collect_course.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_course.user_id
     *
     * @param user_id the value for collect_course.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_course.course_id
     *
     * @return the value of collect_course.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_course.course_id
     *
     * @param course_id the value for collect_course.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCourse_id(Integer course_id) {
        this.course_id = course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_course.collect_time
     *
     * @return the value of collect_course.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getCollect_time() {
        return collect_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_course.collect_time
     *
     * @param collect_time the value for collect_course.collect_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCollect_time(Date collect_time) {
        this.collect_time = collect_time;
    }
}