package top.chao.entity;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.intro
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.learn_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer learn_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.difficulty
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.image
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date publish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer subject_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.direction_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer direction_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.learn_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer learn_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.intro
     *
     * @return the value of course.intro
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.intro
     *
     * @param intro the value for course.intro
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.learn_count
     *
     * @return the value of course.learn_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getLearn_count() {
        return learn_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.learn_count
     *
     * @param learn_count the value for course.learn_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLearn_count(Integer learn_count) {
        this.learn_count = learn_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.difficulty
     *
     * @return the value of course.difficulty
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.difficulty
     *
     * @param difficulty the value for course.difficulty
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty == null ? null : difficulty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.score
     *
     * @return the value of course.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.score
     *
     * @param score the value for course.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.image
     *
     * @return the value of course.image
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.image
     *
     * @param image the value for course.image
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.publish_time
     *
     * @return the value of course.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getPublish_time() {
        return publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.publish_time
     *
     * @param publish_time the value for course.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPublish_time(Date publish_time) {
        this.publish_time = publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject_id
     *
     * @return the value of course.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getSubject_id() {
        return subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject_id
     *
     * @param subject_id the value for course.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setSubject_id(Integer subject_id) {
        this.subject_id = subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.direction_id
     *
     * @return the value of course.direction_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getDirection_id() {
        return direction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.direction_id
     *
     * @param direction_id the value for course.direction_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setDirection_id(Integer direction_id) {
        this.direction_id = direction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.learn_time
     *
     * @return the value of course.learn_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getLearn_time() {
        return learn_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.learn_time
     *
     * @param learn_time the value for course.learn_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLearn_time(Integer learn_time) {
        this.learn_time = learn_time;
    }
}