package top.chao.entity;

import java.util.Date;

public class BrowsingHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer use_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer course_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.browse_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date browse_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer video_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.id
     *
     * @return the value of browsing_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.id
     *
     * @param id the value for browsing_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.use_id
     *
     * @return the value of browsing_history.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUse_id() {
        return use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.use_id
     *
     * @param use_id the value for browsing_history.use_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUse_id(Integer use_id) {
        this.use_id = use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.course_id
     *
     * @return the value of browsing_history.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.course_id
     *
     * @param course_id the value for browsing_history.course_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCourse_id(Integer course_id) {
        this.course_id = course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.browse_time
     *
     * @return the value of browsing_history.browse_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getBrowse_time() {
        return browse_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.browse_time
     *
     * @param browse_time the value for browsing_history.browse_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setBrowse_time(Date browse_time) {
        this.browse_time = browse_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.video_id
     *
     * @return the value of browsing_history.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getVideo_id() {
        return video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.video_id
     *
     * @param video_id the value for browsing_history.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setVideo_id(Integer video_id) {
        this.video_id = video_id;
    }
}