package top.chao.entity;

public class Knowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer subject_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer chapter_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.Id
     *
     * @return the value of knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.Id
     *
     * @param id the value for knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.name
     *
     * @return the value of knowledge.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.name
     *
     * @param name the value for knowledge.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.subject_id
     *
     * @return the value of knowledge.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getSubject_id() {
        return subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.subject_id
     *
     * @param subject_id the value for knowledge.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setSubject_id(Integer subject_id) {
        this.subject_id = subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.chapter_id
     *
     * @return the value of knowledge.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getChapter_id() {
        return chapter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.chapter_id
     *
     * @param chapter_id the value for knowledge.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setChapter_id(Integer chapter_id) {
        this.chapter_id = chapter_id;
    }
}