package top.chao.entity;

import java.util.Date;

public class LoginHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.login_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date login_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.city
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.ip
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.id
     *
     * @return the value of login_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.id
     *
     * @param id the value for login_history.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.user_id
     *
     * @return the value of login_history.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.user_id
     *
     * @param user_id the value for login_history.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.login_time
     *
     * @return the value of login_history.login_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getLogin_time() {
        return login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.login_time
     *
     * @param login_time the value for login_history.login_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLogin_time(Date login_time) {
        this.login_time = login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.city
     *
     * @return the value of login_history.city
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.city
     *
     * @param city the value for login_history.city
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.ip
     *
     * @return the value of login_history.ip
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.ip
     *
     * @param ip the value for login_history.ip
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}