package top.chao.entity;

import java.util.Date;

public class PaperExamRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.record_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer record_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.record_id
     *
     * @return the value of paper_exam_record.record_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getRecord_id() {
        return record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.record_id
     *
     * @param record_id the value for paper_exam_record.record_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setRecord_id(Integer record_id) {
        this.record_id = record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.user_id
     *
     * @return the value of paper_exam_record.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.user_id
     *
     * @param user_id the value for paper_exam_record.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.paper_id
     *
     * @return the value of paper_exam_record.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.paper_id
     *
     * @param paper_id the value for paper_exam_record.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.question_id
     *
     * @return the value of paper_exam_record.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.question_id
     *
     * @param question_id the value for paper_exam_record.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.answer
     *
     * @return the value of paper_exam_record.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.answer
     *
     * @param answer the value for paper_exam_record.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.create_time
     *
     * @return the value of paper_exam_record.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.create_time
     *
     * @param create_time the value for paper_exam_record.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}