package top.chao.entity;

import java.util.Date;

public class Paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer subject_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.limit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer limit_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.createtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.begintime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.endtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.status
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.question_total
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_id
     *
     * @return the value of paper.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_id
     *
     * @param paper_id the value for paper.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.type_id
     *
     * @return the value of paper.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.type_id
     *
     * @param type_id the value for paper.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.user_id
     *
     * @return the value of paper.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.user_id
     *
     * @param user_id the value for paper.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.subject_id
     *
     * @return the value of paper.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getSubject_id() {
        return subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.subject_id
     *
     * @param subject_id the value for paper.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setSubject_id(Integer subject_id) {
        this.subject_id = subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.score
     *
     * @return the value of paper.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.score
     *
     * @param score the value for paper.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.limit_time
     *
     * @return the value of paper.limit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getLimit_time() {
        return limit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.limit_time
     *
     * @param limit_time the value for paper.limit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setLimit_time(Integer limit_time) {
        this.limit_time = limit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.createtime
     *
     * @return the value of paper.createtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.createtime
     *
     * @param createtime the value for paper.createtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.begintime
     *
     * @return the value of paper.begintime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.begintime
     *
     * @param begintime the value for paper.begintime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.endtime
     *
     * @return the value of paper.endtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.endtime
     *
     * @param endtime the value for paper.endtime
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.status
     *
     * @return the value of paper.status
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.status
     *
     * @param status the value for paper.status
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.question_total
     *
     * @return the value of paper.question_total
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_total() {
        return question_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.question_total
     *
     * @param question_total the value for paper.question_total
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_total(Integer question_total) {
        this.question_total = question_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.name
     *
     * @return the value of paper.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.name
     *
     * @param name the value for paper.name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}