package top.chao.entity;

import java.util.Date;

public class PaperScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.total_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer total_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.my_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer my_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.start_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.end_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.Id
     *
     * @return the value of paper_score.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.Id
     *
     * @param id the value for paper_score.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.total_score
     *
     * @return the value of paper_score.total_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getTotal_score() {
        return total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.total_score
     *
     * @param total_score the value for paper_score.total_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setTotal_score(Integer total_score) {
        this.total_score = total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.my_score
     *
     * @return the value of paper_score.my_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getMy_score() {
        return my_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.my_score
     *
     * @param my_score the value for paper_score.my_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setMy_score(Integer my_score) {
        this.my_score = my_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.start_time
     *
     * @return the value of paper_score.start_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.start_time
     *
     * @param start_time the value for paper_score.start_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.end_time
     *
     * @return the value of paper_score.end_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.end_time
     *
     * @param end_time the value for paper_score.end_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.paper_id
     *
     * @return the value of paper_score.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.paper_id
     *
     * @param paper_id the value for paper_score.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.user_id
     *
     * @return the value of paper_score.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.user_id
     *
     * @param user_id the value for paper_score.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}