package top.chao.entity;

public class PaperKnowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer knowledge_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.question_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.id
     *
     * @return the value of paper_knowledge.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.id
     *
     * @param id the value for paper_knowledge.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.paper_id
     *
     * @return the value of paper_knowledge.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.paper_id
     *
     * @param paper_id the value for paper_knowledge.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.knowledge_id
     *
     * @return the value of paper_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getKnowledge_id() {
        return knowledge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.knowledge_id
     *
     * @param knowledge_id the value for paper_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setKnowledge_id(Integer knowledge_id) {
        this.knowledge_id = knowledge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.question_num
     *
     * @return the value of paper_knowledge.question_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_num() {
        return question_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.question_num
     *
     * @param question_num the value for paper_knowledge.question_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_num(Integer question_num) {
        this.question_num = question_num;
    }
}