package top.chao.entity;

public class PaperQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.question_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.paper_id
     *
     * @return the value of paper_question.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.paper_id
     *
     * @param paper_id the value for paper_question.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.question_id
     *
     * @return the value of paper_question.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.question_id
     *
     * @param question_id the value for paper_question.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.question_score
     *
     * @return the value of paper_question.question_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_score() {
        return question_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.question_score
     *
     * @param question_score the value for paper_question.question_score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_score(Integer question_score) {
        this.question_score = question_score;
    }
}