package top.chao.entity;

import java.util.Date;

public class PaperExamReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.report_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer report_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.error_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer error_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.right_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer right_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.submit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date submit_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.content
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.report_id
     *
     * @return the value of paper_exam_report.report_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getReport_id() {
        return report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.report_id
     *
     * @param report_id the value for paper_exam_report.report_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setReport_id(Integer report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.user_id
     *
     * @return the value of paper_exam_report.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.user_id
     *
     * @param user_id the value for paper_exam_report.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.paper_id
     *
     * @return the value of paper_exam_report.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.paper_id
     *
     * @param paper_id the value for paper_exam_report.paper_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.error_num
     *
     * @return the value of paper_exam_report.error_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getError_num() {
        return error_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.error_num
     *
     * @param error_num the value for paper_exam_report.error_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setError_num(Integer error_num) {
        this.error_num = error_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.right_num
     *
     * @return the value of paper_exam_report.right_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getRight_num() {
        return right_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.right_num
     *
     * @param right_num the value for paper_exam_report.right_num
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setRight_num(Integer right_num) {
        this.right_num = right_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.score
     *
     * @return the value of paper_exam_report.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.score
     *
     * @param score the value for paper_exam_report.score
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.submit_time
     *
     * @return the value of paper_exam_report.submit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getSubmit_time() {
        return submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.submit_time
     *
     * @param submit_time the value for paper_exam_report.submit_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setSubmit_time(Date submit_time) {
        this.submit_time = submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.create_time
     *
     * @return the value of paper_exam_report.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.create_time
     *
     * @param create_time the value for paper_exam_report.create_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.content
     *
     * @return the value of paper_exam_report.content
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.content
     *
     * @param content the value for paper_exam_report.content
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}