package top.chao.entity;

public class QuestionOptions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.option_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer option_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.option_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String option_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_id
     *
     * @return the value of question_options.option_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getOption_id() {
        return option_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_id
     *
     * @param option_id the value for question_options.option_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setOption_id(Integer option_id) {
        this.option_id = option_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.question_id
     *
     * @return the value of question_options.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.question_id
     *
     * @param question_id the value for question_options.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_name
     *
     * @return the value of question_options.option_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getOption_name() {
        return option_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_name
     *
     * @param option_name the value for question_options.option_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setOption_name(String option_name) {
        this.option_name = option_name == null ? null : option_name.trim();
    }
}