package top.chao.entity;

public class QuestionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.type_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String type_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.type_id
     *
     * @return the value of question_type.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.type_id
     *
     * @param type_id the value for question_type.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.type_name
     *
     * @return the value of question_type.type_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getType_name() {
        return type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.type_name
     *
     * @param type_name the value for question_type.type_name
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setType_name(String type_name) {
        this.type_name = type_name == null ? null : type_name.trim();
    }
}