package top.chao.entity;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.author
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.add_date
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date add_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.degree
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer knowledge_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer subject_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer chapter_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.author
     *
     * @return the value of question.author
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.author
     *
     * @param author the value for question.author
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.add_date
     *
     * @return the value of question.add_date
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getAdd_date() {
        return add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.add_date
     *
     * @param add_date the value for question.add_date
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setAdd_date(Date add_date) {
        this.add_date = add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.degree
     *
     * @return the value of question.degree
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.degree
     *
     * @param degree the value for question.degree
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type_id
     *
     * @return the value of question.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type_id
     *
     * @param type_id the value for question.type_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.knowledge_id
     *
     * @return the value of question.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getKnowledge_id() {
        return knowledge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.knowledge_id
     *
     * @param knowledge_id the value for question.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setKnowledge_id(Integer knowledge_id) {
        this.knowledge_id = knowledge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.subject_id
     *
     * @return the value of question.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getSubject_id() {
        return subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.subject_id
     *
     * @param subject_id the value for question.subject_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setSubject_id(Integer subject_id) {
        this.subject_id = subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.chapter_id
     *
     * @return the value of question.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getChapter_id() {
        return chapter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.chapter_id
     *
     * @param chapter_id the value for question.chapter_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setChapter_id(Integer chapter_id) {
        this.chapter_id = chapter_id;
    }
}