package top.chao.entity;

public class QuestionKnowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer question_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer knowledge_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.Id
     *
     * @return the value of question_knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.Id
     *
     * @param id the value for question_knowledge.Id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.question_id
     *
     * @return the value of question_knowledge.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.question_id
     *
     * @param question_id the value for question_knowledge.question_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.knowledge_id
     *
     * @return the value of question_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getKnowledge_id() {
        return knowledge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.knowledge_id
     *
     * @param knowledge_id the value for question_knowledge.knowledge_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setKnowledge_id(Integer knowledge_id) {
        this.knowledge_id = knowledge_id;
    }
}