package top.chao.entity;

import java.util.Date;

public class Issue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.headline
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String headline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.issue_context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private String issue_context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Date publish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.answer_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer answer_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.browse_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer browse_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer video_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.right_answer_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    private Integer right_answer_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.id
     *
     * @return the value of issue.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.id
     *
     * @param id the value for issue.id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.headline
     *
     * @return the value of issue.headline
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getHeadline() {
        return headline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.headline
     *
     * @param headline the value for issue.headline
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setHeadline(String headline) {
        this.headline = headline == null ? null : headline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.issue_context
     *
     * @return the value of issue.issue_context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String getIssue_context() {
        return issue_context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.issue_context
     *
     * @param issue_context the value for issue.issue_context
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setIssue_context(String issue_context) {
        this.issue_context = issue_context == null ? null : issue_context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.publish_time
     *
     * @return the value of issue.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Date getPublish_time() {
        return publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.publish_time
     *
     * @param publish_time the value for issue.publish_time
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setPublish_time(Date publish_time) {
        this.publish_time = publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.answer_count
     *
     * @return the value of issue.answer_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getAnswer_count() {
        return answer_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.answer_count
     *
     * @param answer_count the value for issue.answer_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setAnswer_count(Integer answer_count) {
        this.answer_count = answer_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.browse_count
     *
     * @return the value of issue.browse_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getBrowse_count() {
        return browse_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.browse_count
     *
     * @param browse_count the value for issue.browse_count
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setBrowse_count(Integer browse_count) {
        this.browse_count = browse_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.video_id
     *
     * @return the value of issue.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getVideo_id() {
        return video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.video_id
     *
     * @param video_id the value for issue.video_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setVideo_id(Integer video_id) {
        this.video_id = video_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.user_id
     *
     * @return the value of issue.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.user_id
     *
     * @param user_id the value for issue.user_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.right_answer_id
     *
     * @return the value of issue.right_answer_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public Integer getRight_answer_id() {
        return right_answer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.right_answer_id
     *
     * @param right_answer_id the value for issue.right_answer_id
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public void setRight_answer_id(Integer right_answer_id) {
        this.right_answer_id = right_answer_id;
    }
}