package top.chao.dao;

import org.apache.ibatis.jdbc.SQL;
import top.chao.entity.BrowsingHistory;

public class BrowsingHistorySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String insertSelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("browsing_history");
        
        if (record.getUse_id() != null) {
            sql.VALUES("use_id", "#{use_id,jdbcType=INTEGER}");
        }
        
        if (record.getCourse_id() != null) {
            sql.VALUES("course_id", "#{course_id,jdbcType=INTEGER}");
        }
        
        if (record.getBrowse_time() != null) {
            sql.VALUES("browse_time", "#{browse_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideo_id() != null) {
            sql.VALUES("video_id", "#{video_id,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String updateByPrimaryKeySelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.UPDATE("browsing_history");
        
        if (record.getUse_id() != null) {
            sql.SET("use_id = #{use_id,jdbcType=INTEGER}");
        }
        
        if (record.getCourse_id() != null) {
            sql.SET("course_id = #{course_id,jdbcType=INTEGER}");
        }
        
        if (record.getBrowse_time() != null) {
            sql.SET("browse_time = #{browse_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideo_id() != null) {
            sql.SET("video_id = #{video_id,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}