package top.chao.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import top.chao.entity.PaperQuestion;

public interface PaperQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Delete({
        "delete from paper_question",
        "where paper_id = #{paper_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer paper_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Insert({
        "insert into paper_question (paper_id, question_id, ",
        "question_score)",
        "values (#{paper_id,jdbcType=INTEGER}, #{question_id,jdbcType=INTEGER}, ",
        "#{question_score,jdbcType=INTEGER})"
    })
    int insert(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @InsertProvider(type=PaperQuestionSqlProvider.class, method="insertSelective")
    int insertSelective(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Select({
        "select",
        "paper_id, question_id, question_score",
        "from paper_question",
        "where paper_id = #{paper_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="paper_id", property="paper_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="question_id", property="question_id", jdbcType=JdbcType.INTEGER),
        @Result(column="question_score", property="question_score", jdbcType=JdbcType.INTEGER)
    })
    PaperQuestion selectByPrimaryKey(Integer paper_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @UpdateProvider(type=PaperQuestionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Update({
        "update paper_question",
        "set question_id = #{question_id,jdbcType=INTEGER},",
          "question_score = #{question_score,jdbcType=INTEGER}",
        "where paper_id = #{paper_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PaperQuestion record);
}