package top.chao.dao;

import org.apache.ibatis.jdbc.SQL;
import top.chao.entity.QuestionType;

public class QuestionTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String insertSelective(QuestionType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("question_type");
        
        if (record.getType_id() != null) {
            sql.VALUES("type_id", "#{type_id,jdbcType=INTEGER}");
        }
        
        if (record.getType_name() != null) {
            sql.VALUES("type_name", "#{type_name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    public String updateByPrimaryKeySelective(QuestionType record) {
        SQL sql = new SQL();
        sql.UPDATE("question_type");
        
        if (record.getType_name() != null) {
            sql.SET("type_name = #{type_name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("type_id = #{type_id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}