package top.chao.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import top.chao.entity.QuestionOptions;

public interface QuestionOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Delete({
        "delete from question_options",
        "where option_id = #{option_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer option_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Insert({
        "insert into question_options (option_id, question_id, ",
        "option_name)",
        "values (#{option_id,jdbcType=INTEGER}, #{question_id,jdbcType=INTEGER}, ",
        "#{option_name,jdbcType=VARCHAR})"
    })
    int insert(QuestionOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @InsertProvider(type=QuestionOptionsSqlProvider.class, method="insertSelective")
    int insertSelective(QuestionOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Select({
        "select",
        "option_id, question_id, option_name",
        "from question_options",
        "where option_id = #{option_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="option_id", property="option_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="question_id", property="question_id", jdbcType=JdbcType.INTEGER),
        @Result(column="option_name", property="option_name", jdbcType=JdbcType.VARCHAR)
    })
    QuestionOptions selectByPrimaryKey(Integer option_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @UpdateProvider(type=QuestionOptionsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(QuestionOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbg.generated Mon Sep 02 21:19:46 CST 2019
     */
    @Update({
        "update question_options",
        "set question_id = #{question_id,jdbcType=INTEGER},",
          "option_name = #{option_name,jdbcType=VARCHAR}",
        "where option_id = #{option_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(QuestionOptions record);
}